version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.2.0 # Specify the Node.js version you need
    commands:
      - npm install # Install all dependencies
  pre_build:
    commands:
      - npm install -g vite # Ensure Vite is installed globally
  build:
    commands:
      - npm run build # Run the build script
artifacts:
  files:
    - "**/*"
  base-directory: dist # Adjust based on your output directory
